apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wg4vh49mw-nodejs
  janus-idp.io/tekton: wg4vh49mw-nodejs
  backstage.io/kubernetes-id: wg4vh49mw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wg4vh49mw-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
