apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wg4vh49mw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wg4vh49mw-nodejs 
  name: wg4vh49mw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wg4vh49mw-nodejs 
